---
name: Build and Save a Container Image

on:
  workflow_dispatch:

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://markllama.jfrog.io/artifactory
          JF_USER: "markllama@gmail.com"
          JF_PASSWORD: ${{ secrets.JF_ACCESS_TOKEN }}
      - run: |
          # Ping the server
          jf rt ping
