---
name: Build and Save a Container Image

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAME:
        description: Registry Name
        required: true

      REGISTRY_USER:
        description: Registry Username
        required: true
    
jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      # Clond the code
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Build the Image
        shell: bash {0}
        run: |
          make build

      - name: Tag the image for the destination
        shell: bash {0}
        run: |
          make -e tag
          make -e push

          
      - name: Log in to repo
        shell: bash {0}
        run: |
          podman login --username ${{ inputs.REGISTRY_USER }} --password ${{ secrets.JFROG_ACCESS_TOKEN }} ${{ inputs.REGISTRY_NAME }}
          

      # JFROG SETUP? Not really needed.
      # - name: Prepare JFrog CLI
      #   uses: jfrog/setup-jfrog-cli@v3
      #   env:
      #     JF_URL: https://markllama.jfrog.io
      #     JF_USER: "markllama@gmail.com"
      #     JF_PASSWORD: ${{ secrets.JF_ACCESS_TOKEN }}
      # - run: |
      #     # Ping the server
      #     jf rt ping
      # - run: |
      #     jf config export 
